name: chungus
options:
  bundleIdPrefix: com.arjun.chungus.merge
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"

configFiles:
  Debug: Secrets.xcconfig
  Release: Secrets.xcconfig

packages:
  Tun2SocksKit:
    url: https://github.com/EbrahimTahernejad/Tun2SocksKit
    exactVersion: "5.14.4"
  Supabase:
    url: https://github.com/supabase/supabase-swift
    from: "2.0.0"

targets:
  chungus:
    type: application
    platform: iOS
    sources:
      - path: chungus
    dependencies:
      - package: Supabase
      - target: chungusTunnel
      - sdk: NetworkExtension.framework
    info:
      path: chungus/Info.plist
      properties:
        UIAppFonts:
          - SK Pupok Solid 400.ttf
          - Coolvetica Rg.otf
          - Coolvetica Rg It.otf
        UIViewControllerBasedStatusBarAppearance: false
        UIStatusBarStyle: UIStatusBarStyleLightContent
        UILaunchScreen: {}
        SUPABASE_URL: $(SUPABASE_URL)
        SUPABASE_KEY: $(SUPABASE_KEY)
    entitlements:
      path: chungus/chungus.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.arjun.chungus.merge
        INFOPLIST_FILE: chungus/Info.plist
        DEVELOPMENT_TEAM: KSW886X5UX
        ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
        ENABLE_USER_SCRIPT_SANDBOXING: YES

  chungusTunnel:
    type: app-extension
    platform: iOS
    sources:
      - chungusTunnel
    dependencies:
      - package: Tun2SocksKit
      - sdk: NetworkExtension.framework
    info:
      path: chungusTunnel/Info.plist
      properties:
        NSExtension:
          NSExtensionPointIdentifier: com.apple.networkextension.packet-tunnel
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).PacketTunnelProvider
    entitlements:
      path: chungusTunnel/chungusTunnel.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.arjun.chungus.merge.chungusTunnel
        DEVELOPMENT_TEAM: KSW886X5UX
